### ISSUE TITLE
Fails with perl < 5.14.0

### ISSUE THREAD

**Issue by andk** [perl-weasel/weasel#3]
As per subject.  Best illustrated with the matrix: 

http://matrix.cpantesters.org/?dist=Weasel+0.09

Sample fail report: 

http://matrix.cpantesters.org/?dist=Weasel%200.09;os=linux;perl=5.12.5;reports=1

Diagnostics:

Invalid version format (non-numeric data) at t/01-logging.t line 7, near "package DummyDriver "
syntax error at t/01-logging.t line 8, near "package DummyDriver {
    "
Execution of t/01-logging.t aborted due to compilation errors.

If this is intentional, it would be cool if you could declare your requirement. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

HTH&&Thanks,

**Comment by ehuelsmann** [comment]
Thanks for the heads-up. No, it's unintentional. In a year and a half, I'm likely to drop 5.10 and 5.12 support, but currently I'm testing an application with this library which supports as low as 5.10.

I've put Travis CI testing in place now and will make sure to be releasing a 5.10+5.12 compatible version soon.

**Comment by ehuelsmann** [comment]
Fixed by merging 36d646e
